node {

  // job
  try {
    stage('build') {
      println('so far so good...')
      slackSend (channel: slackResponse.channelId, color: '#FF0000', message: "Build: ${env.JOB_NAME} Completed Successfully ${env.BUILD_URL}", timestamp: slackResponse.ts)

    }
    stage('test') {
      println('A test has failed!')
      sh 'exit 1'
    }
  } catch(e) {
    // mark build as failed
    currentBuild.result = "FAILURE";

    // send slack notification
    slackSend (channel: slackResponse.channelId, color: '#FF0000', message: "Build: ${env.JOB_NAME} Completed Successfully ${env.BUILD_URL}", timestamp: slackResponse.ts)

    // throw the error
    throw e;
  }
}
